---
swagger: "2.0"
info:
  description: "buscarUrl-Api"
  version: "2021-01-31T04:53:20Z"
  title: "buscarUrl-Api"
host: "phqmqsb7v1.execute-api.us-east-1.amazonaws.com"
basePath: "/producao"
schemes:
- "https"
paths:
  /{shortid}:
    get:
      consumes:
      - "application/json"
      parameters:
      - name: "shortid"
        in: "path"
        required: true
        type: "string"
      responses:
        301:
          description: "301 response"
          headers:
            Location:
              type: "string"
