---
swagger: "2.0"
info:
  description: "Created by AWS Lambda"
  version: "2021-01-30T19:08:38Z"
  title: "gerarUrl-API"
host: "47f53nbkm0.execute-api.us-east-1.amazonaws.com"
basePath: "/default"
schemes:
- "https"
paths:
  /gerarUrl:
    x-amazon-apigateway-any-method:
      responses:
        200:
          description: "200 response"
